name: dockerhub-description

on:
  push:
    branches: main
    paths:
      - README.md
      - .github/workflows/docker-description.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: gpucibot
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
          repository: rapidsai/rapidsai-cloud-ml
          readme-filepath: ./README.md
